In [1]:
import numpy as np

a_2d = np.array([[10, 20, 30], [40, 50, 60]])
a_1d = np.array([1, 2, 3])

a = a_2d + a_1d
print(a)

[[11 22 33]
 [41 52 63]]


In [3]:
a_2d = np.array([[1, 2], [3, 4]])
a_1d = np.array([10, 20])[:, np.newaxis]

a = a_2d * a_1d
print(a)

[[10 20]
 [60 80]]


In [5]:
a = np.arange(1, 25).reshape(2, 3, 4)
r = a[1]
print(r)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [6]:
r = a[:, :, -1]
print(r)

[[ 4  8 12]
 [16 20 24]]


In [7]:
r = a[::-1]
print(r)

[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [8]:
a[a % 2 == 0] = -1
print(a)

[[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


In [9]:
a1 = np.array([1, 2, 3, 4, 5, 6])
r = np.repeat(a1, np.where(a1 % 2 != 0, 2, 1))
print(r)

[1 1 2 3 3 4 5 5 6]


In [11]:
a1 = np.array([1, 2, 3, 4, 5, 6])
r = np.repeat(a1, a1)
print(r)

[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [15]:
a2 = np.array([10, 20, 30])
norm_a = (a2 - a2.min()) / (a2.max() - a2.min())
print(norm_a,float)

[0.  0.5 1. ] <class 'float'>


In [17]:
i = np.arange(3).reshape(3, 1)
j = np.arange(3)
r = i * j
print(r)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
